services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: monorepo_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      CLIENT_ORIGIN: http://localhost:5173
      DATABASE_URL: postgresql://postgres:Vectordbm1@postgres:5432/monorepo_db
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: monorepo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: monorepo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vectordbm1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d monorepo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
